export const NOTE_GETALL_FAIL = "NOTE_GETALL_FAIL";
export const NOTE_GETALL_REQUEST = "NOTE_GETALL_REQUEST";
export const NOTE_GETALL_SUCCESS = "NOTE_GETALL_SUCCESS";

export const NOTE_GET_FAIL = "NOTE_GET_FAIL";
export const NOTE_GET_REQUEST = "NOTE_GET_REQUEST";
export const NOTE_GET_SUCCESS = "NOTE_GET_SUCCESS";

export const NOTE_ADD_FAIL = "NOTE_ADD_FAIL";
export const NOTE_ADD_REQUEST = "NOTE_ADD_REQUEST";
export const NOTE_ADD_SUCCESS = "NOTE_ADD_SUCCESS";

export const NOTE_UPDATE_FAIL = "NOTE_UPDATE_FAIL";
export const NOTE_UPDATE_REQUEST = "NOTE_UPDATE_REQUEST";
export const NOTE_UPDATE_SUCCESS = "NOTE_UPDATE_SUCCESS";

export const NOTE_DELETE_FAIL = "NOTE_DELETE_FAIL";
export const NOTE_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTE_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";